platform :ios, '6.0' 
pod 'SHGestureRecognizerBlocks', :path => '../'
pod 'SHKeyValueObserverBlocks', :git => "https://github.com/seivan/SHKeyValueObserverBlocks.git", :branch => "release/0.2.0"
pod 'SHSegueBlocks'