platform :ios, '6.0' 
pod 'SHActionSheetBlocks', :path => '../'
pod 'SHSegueBlocks'
pod 'SHBarButtonItemBlocks'
pod 'SHFastEnumerationProtocols'

target :ExampleTests do
  pod 'SHTestCaseAdditions'
  pod "KIF"
end



