platform :ios, '7.0' 

pod 'SHActionSheetBlocks', :path => '../'

target :Sample, :exclusive => true do
  pod 'SHSegueBlocks'
  pod 'SHBarButtonItemBlocks'
  pod 'SHFastEnumerationProtocols'
end

target :LibraryTests, :exclusive => true do
  pod 'SHTestCaseAdditions'
  pod "KIF/XCTest", :git => "https://github.com/tonyd256/KIF", :branch => "xctest"
end



